import {
	AppWindow,
	Binary,
	Blend,
	CalendarDays,
	ClipboardPaste,
	Contrast,
	Crop,
	Crosshair,
	Dices,
	Droplet,
	Droplets,
	Eye,
	FileImage,
	FileOutput,
	FilePlus2,
	Film,
	FlipHorizontal2,
	Focus,
	Frame,
	Grid3x3,
	Hammer,
	Hash,
	Image as ImageIcon,
	Info,
	Layers,
	Link2,
	Maximize2,
	Moon,
	PaintBucket,
	Palette,
	Rainbow,
	Repeat2,
	RotateCw,
	Ruler,
	Scaling,
	Scan,
	Scissors,
	SearchCheck,
	Square,
	Stamp,
	Sun,
	Type,
	ZoomIn,
	ZoomOut
} from '@lucide/svelte';

export const TOOL_ICONS: Record<string, typeof AppWindow> = {
	'resize-png': Scaling,
	'crop-png': Crop,
	'rotate-png': RotateCw,
	'flip-png': FlipHorizontal2,
	'grayscale-png': Contrast,
	'invert-colors-png': Blend,
	'adjust-brightness-contrast-png': Sun,
	'convert-png-to-jpg': FileImage,
	'convert-png-to-webp': FileImage,
	'remove-color-from-png': Scissors,
	'png-info': Info,
	'jpg-to-png': FileImage,
	'webp-to-png': FileImage,
	'gif-to-png': Film,
	'bmp-to-png': FileImage,
	'ico-to-png': AppWindow,
	'png-to-bmp': FileOutput,
	'png-to-base64': Binary,
	'base64-to-png': ClipboardPaste,
	'png-to-data-uri': Link2,
	'data-uri-to-png': ClipboardPaste,
	'png-to-hex': Hash,
	'hex-to-png': Hash,
	'change-png-opacity': Droplet,
	'sepia-png': Palette,
	'change-png-hue': Rainbow,
	'extract-channel-png': Layers,
	'swap-channels-png': Repeat2,
	'black-and-white-png': Contrast,
	'posterize-png': Layers,
	'two-colors-png': Blend,
	'invert-alpha-png': Droplets,
	'remove-alpha-channel-png': Square,
	'set-alpha-channel-png': Droplet,
	'extract-alpha-mask-png': Layers,
	'round-corners-png': Frame,
	'add-padding-png': Maximize2,
	'add-border-png': Frame,
	'fit-on-background-png': ImageIcon,
	'tile-png': Grid3x3,
	'center-by-alpha-png': Crosshair,
	'create-empty-png': FilePlus2,
	'single-color-png': PaintBucket,
	'random-noise-png': Dices,
	'linear-gradient-png': Sun,
	'png-is-grayscale': SearchCheck,
	'png-is-transparent': Eye,
	'png-orientation': Ruler,
	'blur-png': Droplets,
	'sharpen-png': Focus,
	'remove-background-png': Scissors,
	'add-stroke-png': Square,
	'add-text-png': Type,
	'date-stamp-png': CalendarDays,
	'png-to-hsl': Blend,
	'png-to-hsv': Droplet,
	'png-to-hsi': Focus,
	'png-to-cmyk': PaintBucket,
	'png-to-ycbcr': Layers,
	'png-to-lab': Ruler,
	'show-transparent-png': Eye,
	'show-grayscale-pixels-png': Contrast,
	'show-color-pixels-png': Rainbow,
	'light-pixel-mask-png': Sun,
	'dark-pixel-mask-png': Moon,
	'unique-color-mask-png': Dices,
	'extract-color-from-png': Focus,
	'watermark-tile-png': Stamp,
	'watermark-image-png': FileImage,
	'color-wheel-png': Rainbow,
	'complementary-png': Contrast,
	'triadic-png': Hash,
	'tetradic-png': Grid3x3,
	'analogous-png': Blend,
	'monochromatic-png': Droplets,
	'shades-png': Sun,
	'mix-colors-png': PaintBucket,
	'blend-two-png': Layers,
	'step-colors-png': Scaling,
	'sort-colors-png': SearchCheck,
	'find-contour-png': Scan,
	'make-thicker-png': ZoomIn,
	'make-thinner-png': ZoomOut,
	'harden-alpha-png': Sun,
	'despeckle-alpha-png': SearchCheck,
	'close-holes-png': Hammer,
	'skew-png': Repeat2,
	'rotate-free-png': RotateCw,
	'zoom-png': ZoomIn,
	'shift-png': Crosshair,
	'vignette-png': Sun,
	'jpeg-artifacts-png': Layers,
	'gamma-png': Contrast,
	'auto-contrast-png': Contrast,
	'temperature-png': Sun,
	'tint-png': Droplet,
	'svg-to-png': FileImage
};
